version: '3.7'

services:
    bisq-bitcoind:
        image: bisq/bitcoind:latest
        volumes:
            - ./bitcoind_data_dir:/root/.bitcoin
        command:
            - -regtest
            - -server=1
            - -listen=1
            - -discover=1
            - -txindex=1
            - -dbcache=1337
            - -maxconnections=1337
            - -peerbloomfilters=1
            - -onion=bisq-tor:9050
            - -rpcallowip=127.0.0.1
            - -rpcallowip=172.0.0.1/8 # Docker IP range
            - -rpcuser=${BITCOIN_RPC_USER}
            - -rpcpassword=${BITCOIN_RPC_PASS}
            - -blocknotify=/root/.bitcoin/blocknotify.sh %s
            - -bind=0.0.0.0:${BITCOIN_RPC_PORT}
            - -rpcbind=0.0.0.0:${BITCOIN_RPC_PORT}

    bisq-seednode-1:
        image: bisq/seednode:latest
        depends_on:
            - bisq-bitcoind
        extra_hosts:
            - host.docker.internal:host-gateway
        ports:
            - 2002:2002 # bisq node port
            - 5120:5120 # bitcoind rpc block notifications
        volumes:
            - bisq_seednode_1_data:/bisq/bisq-seednode
        command:
            - --baseCurrencyNetwork=${BISQ_BASE_CURRENCY}
            - --useLocalhostForP2P=true
            - --useDevPrivilegeKeys=true
            - --fullDaoNode=${BISQ_DAO_FULLNODE}
            - --btcNodes=${BITCOIN_P2P_HOST}:${BITCOIN_P2P_PORT}
            - --rpcHost=${BITCOIN_RPC_HOST}
            - --rpcPort=${BITCOIN_RPC_PORT}
            - --rpcUser=${BITCOIN_RPC_USER}
            - --rpcPassword=${BITCOIN_RPC_PASS}
            - --rpcBlockNotificationPort=5120
            - --nodePort=2002
            - --userDataDir=${BISQ_HOME}
            - --appName=${BISQ_APP_NAME}

    bisq-seednode-2:
        image: bisq/seednode:latest
        depends_on:
            - bisq-bitcoind
        extra_hosts:
            - host.docker.internal:host-gateway
        ports:
            - 3002:3002 # bisq node port
            - 5121:5121 # bitcoind rpc block notifications
        volumes:
            - bisq_seednode_2_data:/bisq/bisq-seednode
        command:
            - --baseCurrencyNetwork=${BISQ_BASE_CURRENCY}
            - --useLocalhostForP2P=true
            - --useDevPrivilegeKeys=true
            - --fullDaoNode=${BISQ_DAO_FULLNODE}
            - --btcNodes=${BITCOIN_P2P_HOST}:${BITCOIN_P2P_PORT}
            - --rpcHost=${BITCOIN_RPC_HOST}
            - --rpcPort=${BITCOIN_RPC_PORT}
            - --rpcUser=${BITCOIN_RPC_USER}
            - --rpcPassword=${BITCOIN_RPC_PASS}
            - --rpcBlockNotificationPort=5121
            - --nodePort=3002
            - --userDataDir=${BISQ_HOME}
            - --appName=${BISQ_APP_NAME}

    bisq-tor:
        image: bisq/tor:latest
        extra_hosts:
            - host.docker.internal:host-gateway
        command: [ "--allow-missing-torrc",
                   "--SOCKSPort", "0.0.0.0:9050",
                   "--ControlPort", "0.0.0.0:9051",
                   "--HashedControlPassword", "16:ED08CEBE4E91EA126089506E2880119E20A39054754D3916EAFF774046", # password: bisq
                   "--Log", "notice",
                   "--SafeSocks", "0",
                   "--HiddenServiceStatistics", "0",
                   "--AvoidDiskWrites", "1" ]

volumes:
    bisq_seednode_1_data:
    bisq_seednode_2_data:
