version: '3.7'

services:
    bisq-seednode:
        image: bisq/seednode:latest
        deploy:
            replicas: 1
            restart_policy:
                condition: any
        extra_hosts:
            - host.docker.internal:host-gateway
        ports:
            - 127.0.0.1:5120:5120 # bitcoind rpc block notifications
        volumes:
            - bisq_data:/bisq/bisq-seednode
        command:
            - --fullDaoNode=${BISQ_DAO_FULLNODE}
            - --userDataDir=${BISQ_HOME}
            - --appName=${BISQ_APP_NAME}
            - --baseCurrencyNetwork=${BISQ_BASE_CURRENCY}
            - --maxConnections=${BISQ_MAX_CONNECTIONS}
            - --maxMemory=${BISQ_MAX_MEMORY}
            - --nodePort=${BISQ_NODE_PORT}
            - --btcNodes=${BITCOIN_P2P_HOST}:${BITCOIN_P2P_PORT}
            - --rpcBlockNotificationHost=${BITCOIN_RPC_BLOCKNOTIFY_HOST}
            - --rpcBlockNotificationPort=${BITCOIN_RPC_BLOCKNOTIFY_PORT}
            - --rpcHost=${BITCOIN_RPC_HOST}
            - --rpcPort=${BITCOIN_RPC_PORT}
            - --rpcUser=${BITCOIN_RPC_USER}
            - --rpcPassword=${BITCOIN_RPC_PASS}
            - --dumpBlockchainData=${BISQ_DUMP_BLOCKCHAIN}
            - --dumpStatistics=${BISQ_DUMP_STATISTICS}
            - --torControlHost=bisq-tor
            - --torControlPort=9051
            - --torControlPassword=bisq

    bisq-tor:
        image: bisq/tor:latest
        deploy:
            replicas: 1
            restart_policy:
                condition: any
        volumes:
            - tor_data:/root/.tor
        command: [ "--allow-missing-torrc",
                   "--SOCKSPort", "0.0.0.0:9050",
                   "--ControlPort", "0.0.0.0:9051",
                   "--HashedControlPassword", "16:ED08CEBE4E91EA126089506E2880119E20A39054754D3916EAFF774046", # password: bisq
                   "--Log", "notice syslog",
                   "--SafeSocks", "0",
                   "--HiddenServiceStatistics", "0",
                   "--AvoidDiskWrites", "1" ]

volumes:
    bisq_data:
    tor_data:
