version: '3.7'

services:
    bisq-bitcoind:
        image: bisq/bitcoind:latest
        deploy:
            replicas: 1
            restart_policy:
                condition: any
        ports:
            - 8333:8333 # bitcoind port
        volumes:
            - ./bitcoind_data_dir:/root/.bitcoin
        command:
            - -server=1
            - -listen=1
            - -discover=1
            - -txindex=1
            - -dbcache=1337
            - -maxconnections=1337
            - -peerbloomfilters=1
            - -onion=bisq-tor:9050
            - -rpcallowip=127.0.0.1
            - -rpcallowip=172.0.0.1/8 # Docker IP range
            - -rpcuser=${BITCOIN_RPC_USER}
            - -rpcpassword=${BITCOIN_RPC_PASS}
            - -blocknotify=/root/.bitcoin/blocknotify.sh %s
            - -bind=0.0.0.0:${BITCOIN_RPC_PORT}
            - -rpcbind=0.0.0.0:${BITCOIN_RPC_PORT}

    bisq-seednode:
        image: bisq/seednode:latest
        depends_on:
            - bisq-bitcoind
        deploy:
            replicas: 1
            restart_policy:
                condition: any
        extra_hosts:
            - host.docker.internal:host-gateway
        ports:
            - ${BISQ_NODE_PORT}:${BISQ_NODE_PORT} # bisq node port
            - 127.0.0.1:5120:5120 # bitcoind rpc block notifications
        volumes:
            - bisq_seednode_data:/bisq/bisq-seednode
        command:
            - --fullDaoNode=${BISQ_DAO_FULLNODE}
            - --userDataDir=${BISQ_HOME}
            - --appName=${BISQ_APP_NAME}
            - --baseCurrencyNetwork=${BISQ_BASE_CURRENCY}
            - --maxConnections=${BISQ_MAX_CONNECTIONS}
            - --maxMemory=${BISQ_MAX_MEMORY}
            - --nodePort=${BISQ_NODE_PORT}
            - --btcNodes=${BITCOIN_P2P_HOST}:${BITCOIN_P2P_PORT}
            - --rpcBlockNotificationHost=${BITCOIN_RPC_BLOCKNOTIFY_HOST}
            - --rpcBlockNotificationPort=${BITCOIN_RPC_BLOCKNOTIFY_PORT}
            - --rpcHost=${BITCOIN_RPC_HOST}
            - --rpcPort=${BITCOIN_RPC_PORT}
            - --rpcUser=${BITCOIN_RPC_USER}
            - --rpcPassword=${BITCOIN_RPC_PASS}
            - --dumpBlockchainData=${BISQ_DUMP_BLOCKCHAIN}
            - --dumpStatistics=${BISQ_DUMP_STATISTICS}
            - --torControlHost=bisq-tor
            - --torControlPort=9051
            - --torControlPassword=bisq

    bisq-tor:
        image: bisq/tor:latest
        deploy:
            replicas: 1
            restart_policy:
                condition: any
        volumes:
            - tor_data:/root/.tor
        command: [ "--allow-missing-torrc",
                   "--SOCKSPort", "0.0.0.0:9050",
                   "--ControlPort", "0.0.0.0:9051",
                   "--HashedControlPassword", "16:ED08CEBE4E91EA126089506E2880119E20A39054754D3916EAFF774046", # password: bisq
                   "--Log", "notice",
                   "--SafeSocks", "0",
                   "--HiddenServiceStatistics", "0",
                   "--AvoidDiskWrites", "1" ]

volumes:
    bisq_seednode_data:
    tor_data:
